// Render an AI fit-analysis (Analysis) into a clean, self-contained LaTeX report that
// compiles through the SAME Tectonic pipeline as resumes (no browser PDF generation).
// Content only — the layout/typography is fixed here, deterministic.
import type { Analysis } from "./analyze";

/** Escape user/AI text for safe insertion into LaTeX. */
function esc(s: string): string {
  return (s ?? "")
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/([&%$#_{}])/g, "\\$1")
    .replace(/~/g, "\\textasciitilde{}")
    .replace(/\^/g, "\\textasciicircum{}");
}

function itemize(items: string[]): string {
  const clean = items.filter((x) => x && x.trim());
  if (clean.length === 0) return "\\textit{None identified.}";
  return "\\begin{itemize}[leftmargin=1.2em,itemsep=1pt,topsep=2pt]\n" +
    clean.map((i) => `  \\item ${esc(i)}`).join("\n") +
    "\n\\end{itemize}";
}

function chips(items: string[]): string {
  const clean = items.filter((x) => x && x.trim());
  if (clean.length === 0) return "\\textit{None.}";
  return clean.map((i) => esc(i)).join(" \\quad\\textbullet\\quad ");
}

/** Build the full LaTeX document for an analysis report. */
export function analysisReportLatex(a: Analysis, opts: { title?: string } = {}): string {
  const title = esc(opts.title || "Resume Fit Analysis");
  const gapsBlock = a.gaps.length
    ? "\\begin{itemize}[leftmargin=1.2em,itemsep=3pt,topsep=2pt]\n" +
      a.gaps.map((g) =>
        `  \\item \\textbf{${esc(g.skill)}} \\hfill {\\small\\color{gray}${esc(g.severity)} \\textbullet\\ ${esc(g.timeToBridge)}}\\\\ ${esc(g.action)}`,
      ).join("\n") +
      "\n\\end{itemize}"
    : "\\textit{No significant gaps identified.}";

  const rolesBlock = a.suggestedRoles.length
    ? "\\begin{itemize}[leftmargin=1.2em,itemsep=3pt,topsep=2pt]\n" +
      a.suggestedRoles.map((r) =>
        `  \\item \\textbf{${esc(r.title)}} \\hfill {\\small\\color{gray}${r.matchScore}\\% \\textbullet\\ ${esc(r.prepTime)}}\\\\ ${esc(r.whyFit)}`,
      ).join("\n") +
      "\n\\end{itemize}"
    : "\\textit{None suggested.}";

  return `\\documentclass[a4paper,11pt]{article}
\\usepackage[margin=0.7in,top=0.6in,bottom=0.6in]{geometry}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{xcolor}
\\usepackage{titlesec}
\\usepackage{parskip}
\\definecolor{brand}{RGB}{37,99,235}
\\definecolor{gray}{RGB}{110,110,110}
\\pagenumbering{gobble}
\\titleformat{\\section}{\\large\\bfseries\\color{brand}}{}{0em}{}[\\vspace{-4pt}\\color{brand!30}\\titlerule]
\\titlespacing*{\\section}{0pt}{12pt}{4pt}
\\setlength{\\parskip}{3pt}
\\begin{document}
\\begin{center}
  {\\Huge \\textbf{Aptora}}\\\\[2pt]
  {\\large ${title}}\\\\[4pt]
  {\\color{gray}\\small Target role: \\textbf{${esc(a.targetRole)}}}
\\end{center}
\\vspace{6pt}

\\begin{center}
  \\begin{tabular}{ccc}
    {\\Huge\\bfseries\\color{brand}${a.alignment}\\%} & {\\Huge\\bfseries${a.identityMatch}\\%} & {\\large\\bfseries${esc(a.prepTimeEstimate)}} \\\\
    {\\small\\color{gray}Role fit} & {\\small\\color{gray}Profile match} & {\\small\\color{gray}Est. prep time} \\\\
  \\end{tabular}
\\end{center}
\\vspace{2pt}
\\begin{center}\\small\\itshape ${esc(a.prepSummary)}\\end{center}

\\section*{Strong Matches}
${itemize(a.matched)}

\\section*{Missing / To Strengthen}
${chips(a.missing)}

\\section*{Skill Gaps \\& Actions}
${gapsBlock}

\\section*{Opportunities}
${itemize(a.opportunities)}

\\section*{Suggested Roles}
${rolesBlock}

\\vfill
\\begin{center}{\\footnotesize\\color{gray}Generated by Aptora \\textbullet\\ aptora.enally.in}\\end{center}
\\end{document}
`;
}
